CREATE OR REPLACE TABLE temp_programs AS
SELECT * 
FROM programs
WHERE 1=0; 

INSERT INTO temp_programs (PROGRAM_ID, PROGRAM, PROGRAM_EFFECTIVE_YEAR, PROGRAM_DISCOUNT, UPDATED_AT) 
SELECT PROGRAM_ID, PROGRAM, PROGRAM_EFFECTIVE_YEAR, PROGRAM_DISCOUNT, UPDATED_AT
FROM (
    SELECT PROGRAM_ID, PROGRAM, PROGRAM_EFFECTIVE_YEAR, PROGRAM_DISCOUNT, UPDATED_AT,
           ROW_NUMBER() OVER (PARTITION BY PROGRAM_ID ORDER BY UPDATED_AT DESC) AS row_num
    FROM programs
)
WHERE row_num = 1;

TRUNCATE TABLE programs;

INSERT INTO programs
SELECT * FROM temp_programs;

DROP TABLE IF EXISTS temp_programs;