CREATE OR REPLACE TABLE temp_appliances AS
SELECT * 
FROM appliances
WHERE 1=0; 

INSERT INTO temp_appliances (APPLIANCE_ID, APPLIANCE_NAME, APPLIANCE_TYPE, PRICE, UPDATED_AT) 
SELECT APPLIANCE_ID, APPLIANCE_NAME, APPLIANCE_TYPE, PRICE, UPDATED_AT
FROM (
    SELECT APPLIANCE_ID, APPLIANCE_NAME, APPLIANCE_TYPE, PRICE, UPDATED_AT,
           ROW_NUMBER() OVER (PARTITION BY APPLIANCE_ID ORDER BY UPDATED_AT DESC) AS row_num
    FROM appliances
)
WHERE row_num = 1;

TRUNCATE TABLE appliances;

INSERT INTO appliances
SELECT * FROM temp_appliances;

DROP TABLE IF EXISTS temp_appliances;