deployment:
    configuration:
        name: astronomer-deployment
        description: "Add a description"
        runtime_version: 9.6.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: us-central1
        workspace_name: Data
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-central1
    worker_queues:
        - name: default
          max_worker_count: 10
          min_worker_count: 0
          worker_concurrency: 5
          worker_type: a5
    metadata:
        deployment_id: clprbpkxa208466wixwm8d8lmso
        workspace_id: clhkq9a4f009j01j8yije1caw
        cluster_id: us-central1
        release_name: N/A
        airflow_version: 2.7.3
        current_tag: 9.6.0
        status: HEALTHY
        created_at: 2023-12-04T19:47:40.462Z
        updated_at: 2023-12-04T19:47:40.462Z
        deployment_url: cloud.astronomer.io/clhkq9a4f009j01j8yije1caw/deployments/clprbpkxa208466wixwm8d8lmso/analytics
        webserver_url: demo-org.astronomer.run/d8d8lmso?orgId=org_1OpUayQIEdLg5juV
        workload_identity: astro-weightless-atmosphere-07@astro-us-central1-0001.iam.gserviceaccount.com

