deployment:
    configuration:
        name: astronomer-template-deployment
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        description: <Template deployment for workshop>
        runtime_version: 9.6.0
        dag_deploy_enabled: true
        executor: CeleryExecutor
        cluster_name: us-east-1
        region: us-central1
        workspace_name: "Data"
        scheduler_size: small